version: '3.9'

networks:
  app_network:

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "${APP_PORT}:80"
    environment:
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:${DATABASE_PORT}/${DATABASE_NAME}?serverVersion=mariadb-10.7.3
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network

  database:
    image: mariadb:10.7.3
    restart: always
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_ROOT_PASSWORD}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
    volumes:
      - database_data:/var/lib/mysql
      - ./docker/mariadb/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${DATABASE_ADMIN_PORT}:80"
    environment:
      PMA_HOST: database
    depends_on:
      - database
    networks:
      - app_network

volumes:
  database_data: