version: '3.9'

networks:
  app_network:

services:

  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 8443:443
    depends_on:
      - php
      - database
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./:/var/www/app
    networks:
      - app_network

  database:
    image: mariadb:10.7.3
    restart: always
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_ROOT_PASSWORD}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: "pepa-linha"
    depends_on:
      - php
      - database
    networks:
      - app_network
      
volumes:
  database_data: